### ISSUE TITLE
Exception: 'NoneType' object...

### ISSUE THREAD

**Issue by LMdeLiangMi** [alexattia/SimpsonRecognition#2]
Exception: 'NoneType' object has no attribute 'getitem'
or
Exception: 'NoneType' object is no subscriptable
or
Exception: a must be non-empty

what is the reason of these exceptions?

**Comment by alexattia** [comment]
`Exception: 'NoneType' object is no subscriptable` due toe Y1, computed by the function roi_helpers.calc_iou, is `None`.  It's probably due to that the Intersection-overUnion
(IoU) overlap < classifier_min_overlap (= 0.1 if you didn't change it).
