### ISSUE TITLE
Training the faster rcnn

### ISSUE THREAD

**Issue by yuval7451** [alexattia/SimpsonRecognition#7]
i am trying to train the faster rcnn one the dataset you have provided via kaggle,
while training i am geting an error: 

3/100 [..............................] - ETA: 8:11 - rpn_cls: 0.0000e+00 - rpn_regr: 0.0000e+00 - detector_cls: 5.0297 - detector_regr: 0.9954 'NoneType' object has no attribute 'shape' Exception: 'NoneType' object is not subscriptable

though the training continues i am intersted to know what is this "NoneType object"
  any insight about the issue ? 

Thanks.

**Comment by alexattia** [comment]
It's a warning exception thrown during the training but the training continues. I don't remember exactly where this exception comes from as the [Faster R-CNN implementation in Keras ](https://github.com/yhenon/keras-frcnn/blob/396d54be264e29fcba74398a945e571633835f15/README.md) is now deprecated and replaced by RetinaNet.   
I didn't update this repo with the new algorithm
